version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    depends_on:
      - db
      - redis
      - sidekiq
    restart: always
  redis:
    image: redis:6.2
    command: redis-server
    restart: always
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    environment:
      REDIS_URL: "redis://redis:6379/1"
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app:cached
    restart: always
  db:
    image: postgres:14.11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    command: "postgres -c 'max_connections=500'"
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: {}
networks:
  default:
    name: youtube_video_sharing_app
