version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    depends_on:
      - db
  db:
    image: postgres:14.11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: {}
networks:
  default:
    name: youtube_video_sharing_app
