WEBSOCKET_HOST: 'ws://localhost:3000/cable'
DB_USERNAME: 'postgres'
DB_PASSWORD: 'postgres'
REDIS_SIDEKIQ_URL: 'redis://redis:6379/0'

development:
  DB_NAME: 'youtube_video_sharing_app_development'

test:
  DB_NAME: 'youtube_video_sharing_app_test'
