WEBSOCKET_HOST: 'ws://localhost:3000/cable'

DB_HOST: 'db'
DB_USERNAME: 'postgres'
DB_PASSWORD: 'postgres'

development:
  DB_NAME: 'youtube_video_sharing_app_development'
  REDIS_SIDEKIQ_URL: 'redis://redis:6379/0'

test:
  BASE_URL: 'localhost:3000'
  DB_NAME: 'youtube_video_sharing_app_test'
  REDIS_SIDEKIQ_URL: 'redis://redis:6379/0'
