development:
  adapter: redis
  url: <%= ENV['REDIS_WEB_URL'] %>

test:
  adapter: redis
  url: <%= ENV['REDIS_WEB_URL'] %>

staging:
  adapter: redis
  url: <%= ENV['REDIS_WEB_URL'] %>

production:
  adapter: redis
  url: <%= ENV['REDIS_WEB_URL'] %>
